imports:
  - path: common.py
  - path: deployment.py
  - path: vpc.py
  - path: vm.py

# Check your environment variables file for values!
resources:
  - name: "TODO-PROVIDE-THIS-VALUE"
    type: deployment.py
    properties:
      prefix: "TODO-PROVIDE-THIS-VALUE"
      ipCidrRange: "TODO-PROVIDE-THIS-VALUE"
      region: "TODO-PROVIDE-THIS-VALUE"
      zone: "TODO-PROVIDE-THIS-VALUE"
      source_image: "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9"
      public_key: "TODO-PROVIDE-THIS-VALUE"

